### ISSUE TITLE
check existing rows in Socrata upcoming demolition dataset

### ISSUE THREAD

**Issue by jmcbroom** [CityOfDetroit/demo-alerts#1]
A parcel might receive a `Planned Demo Date` & get pulled into Socrata. 

The next day, the demo gets canceled for whatever reason, and the Salesforce field resets to null.

It would stay in the Socrata dataset since it wouldn't get pulled into the next day's query.

proposed alternative:
1) upsert all `Account`s with a planned knockdown date into Socrata
2) check Socrata dataset against Salesforce 1-by-1 to determine changes each day, instead of relying on an upsert operation from the above query

or, can we check Salesforce for records where only that field has changed?

**Comment by jessicamcinchak** [comment]
no longer an issue since we're using pre-existing socrata datasets
